name: Manage Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:

  label-pr:
    name: Label PR
    if: github.event.action != 'edited'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels/labeler.yaml
          sync-labels: false
          dot: true

  lint-pr-title:
    name: Lint PR title
    if: github.event.action != 'edited' || github.event.changes.title != null
    runs-on: ubuntu-latest

    steps:
      - name: Set up Commitizen
        uses: commitizen-tools/setup-cz@7247d00792cbaf3408d7f8d2c6a010ca3b40c10e # v0.9.0
        with:
          python-version: '3.x'
          version: '4.13.10'

      - name: Lint pull request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: cz check --message "$PR_TITLE"
