name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/test-environment.yaml
      - assets/**
      - flake.nix
      - flake.lock
      - home-modules/**
      - scripts/apply.sh
      - scripts/bootstrap-host.sh
      - scripts/setup.sh
      - tests/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/test-environment.yaml
      - assets/**
      - flake.nix
      - flake.lock
      - home-modules/**
      - scripts/apply.sh
      - scripts/bootstrap-host.sh
      - scripts/setup.sh
      - tests/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  script-based:
    name: Test script-based setup
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04
        entry-point:
          - apply
          - setup
    uses: ./.github/workflows/test-environment.yaml
    with:
      setup-mode: script-based
      entry-point: ${{ matrix.entry-point }}
      os: ${{ matrix.os }}
      common-repository: ${{ github.repository }}
      common-ref: ${{ github.sha }}
      timeout-minutes: 15

  repository-based:
    name: Test config-repository-based setup
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04
    uses: ./.github/workflows/test-environment.yaml
    with:
      setup-mode: repository-based
      os: ${{ matrix.os }}
      common-repository: ${{ github.repository }}
      common-ref: ${{ github.sha }}
      user-repository: ut-issl/personal-nix-config-template
      user-ref: 710819df83c6984834f82ae9dde7603a00416ef8 # main
      override-issl-input: true
      timeout-minutes: 15
