name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/test-environment.yaml
      - assets/**
      - flake.nix
      - flake.lock
      - home-modules/**
      - scripts/apply.sh
      - tests/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/test-environment.yaml
      - assets/**
      - flake.nix
      - flake.lock
      - home-modules/**
      - scripts/apply.sh
      - tests/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  script-based:
    name: Test script-based setup
    uses: ./.github/workflows/test-environment.yaml
    with:
      setup-mode: script-based
      common-repository: ${{ github.repository }}
      common-ref: ${{ github.sha }}

  repository-based:
    name: Test config-repository-based setup
    uses: ./.github/workflows/test-environment.yaml
    with:
      setup-mode: repository-based
      common-repository: ${{ github.repository }}
      common-ref: ${{ github.sha }}
      user-repository: ut-issl/personal-nix-config-template
      user-ref: 638a464289a85838df574b153e1418e5366aeba9 # main
      override-issl-input: true
